### PR TITLE
civility adjustment

### PR DESCRIPTION
**Pull request by FND**

### CODE REVIEW

**Comment by FND** [comment]
I'm not sure you do, given the typo's still in there...

`s/asspects/aspects/` #jokeexplainer

**Comment by eins78** [comment]
Sure, but this PR doesn't fix this typo so it's closed. Thanks anyhow.

**Comment by FND** [comment]
Sorry, the previous comment might have come out a little aggressive, though it wasn't meant to. Anyway, to save you the trouble: #14

**Comment by eins78** [comment]
Oh, I did not see this before just now.
I had already took the hint piped the whole docs through a spellchecker :)

**Comment by FND** [comment]
:+1:

**Pull request closed without merging**
